updated reset axis sliders
hubmapconsortium/ccf-ui pull request #1126
Opened 2023-09-26 20:11 UTC by rchavan10

2023-09-28 19:41 UTC, axdanbol requested changes

2023-09-28 19:41 UTC, axdanbol commented on projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.html
> +  <!-- <mat-icon matRipple [matRippleCentered]="true" [matRippleUnbounded]="true" class="icon reset" (click)="resetRotation()">refresh</mat-icon> -->
Remove commented out code

2023-09-28 19:41 UTC, axdanbol commented on projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.ts
> +  resetRotation(slider: number): void {
Rename slider input to dimension and change its type to `'x' | 'y' | 'z'`
Then you can simplify the update to `this.rotation = { ...this.rotation, [dimension]: 0 }`
It is also easier to see what is updated rather that having to remember that x <-> 1, y <-> 2, and z <-> 3

2023-10-03 19:18 UTC, bherr2 approved these changes

2023-10-03 19:19 UTC, merged