R UI integration issues
hubmapconsortium/ccf-ui pull request #1130
Opened 2023-09-28 17:23 UTC by edlu77

Resolves issues in https://github.com/hubmapconsortium/ccf-ui/milestone/7

2023-09-28 20:09 UTC, axdanbol requested changes

2023-09-28 20:09 UTC, axdanbol commented on projects/ccf-rui/src/app/modules/registration-modal/registration-content/registration-content.component.ts
> +    page.user$.subscribe(user => this.checkNameValid(user));
You should call `cdr.markForCheck()` in these subscribe calls to be on the safe side

2023-09-28 20:09 UTC, axdanbol commented on projects/ccf-rui/src/app/modules/registration-modal/registration-modal/registration-modal.component.ts
> +      debounceTime(1000),
Why increase the debounce time?

2023-09-28 20:09 UTC, axdanbol commented on projects/ccf-rui/src/index.html
> +  <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Sharp" rel="stylesheet">
This might affect other icons as well. Is that what we want?

2023-09-28 20:09 UTC, axdanbol commented on projects/ccf-rui/src/webcomponent-inject-example.html
> +        setTimeout(() => {
Do we really need a timeout again?

2023-09-28 21:03 UTC, edlu77 commented on projects/ccf-rui/src/app/app-web-component.component.ts
> -        organ: BP.json,
It doesn't work when I input organ as a string, that's why I removed it. Is there another way to do it?

2023-09-28 21:06 UTC, edlu77 commented on projects/ccf-rui/src/app/core/store/registration/registration.state.ts
> +        debounceTime(1000),
I was running into weird issues with timing so I was trying out different things. Probably don't need this anymore.

2023-10-04 15:00 UTC, bherr2 approved these changes

2023-10-04 15:00 UTC, merged