Use hybrid database for fetching requests
hubmapconsortium/ccf-ui pull request #1224
Opened 2024-01-29 23:22 UTC by edlu77

#1202

2024-01-30 13:01 UTC, bherr2 reviewed
You'll also need to make sure we don't have default data sources in environment anymore, since that would enable the hybrid option always.

2024-01-30 16:22 UTC, axdanbol requested changes
Some minor tweaks

2024-01-30 16:22 UTC, axdanbol commented on projects/ccf-shared/src/lib/services/data-source/ccf-database.service.ts
> +export class MixedCCfDatabaseDatasourceService extends ForwardingDataSource {
Rename to HybridCCfDatabaseDatasourceService

2024-01-30 16:22 UTC, axdanbol commented on projects/ccf-shared/src/lib/services/data-source/ccf-database.service.ts
> +      (FILTER_METHODS_ARG_0.includes(method) && this.isDefaultFilter(args[0] as Filter)) ||
Lets remove the filter method checks since it should always use local for those.

2024-01-30 16:22 UTC, axdanbol commented on projects/ccf-shared/src/lib/services/data-source/ccf-database.service.ts
> +  private isDefaultFilter(value?: Filter): boolean {
Remove along with the filter method checks

2024-01-30 16:22 UTC, axdanbol commented on projects/ccf-shared/src/lib/services/data-source/api-endpoint.service.ts
> +export type RequestMethod<P, T> = (params: P) => Observable<T>;
Why are you exporting all of these types/functions? Please undo these changes if not needed

2024-02-05 18:00 UTC, axdanbol requested changes
Small tweaks

2024-02-05 18:00 UTC, axdanbol commented on projects/ccf-shared/src/lib/services/data-source/ccf-database.service.ts
> +export const DEFAULT_FILTER: Filter = {
Move back to original location in eui

2024-02-05 18:00 UTC, axdanbol commented on projects/ccf-shared/src/lib/services/data-source/ccf-database.service.ts
> +      (FILTER_METHODS_ARG_0.includes(method)) ||
Remove `FILTER_METHODS_ARG_X` checks. Only `REMOTE_METHODS` should call the remote

2024-02-05 18:00 UTC, axdanbol commented on projects/ccf-eui/src/environments/environment.prod.ts
> +    // dataSources: [
Remove commented out code

2024-02-05 18:00 UTC, axdanbol commented on projects/ccf-eui/src/environments/environment.staging.ts
> +    // dataSources: [
Remove commented out code

2024-02-05 18:00 UTC, axdanbol commented on projects/ccf-eui/src/environments/environment.ts
> +    // dataSources: [
Remove commented out code

2024-02-05 19:37 UTC, axdanbol approved these changes

2024-02-05 19:37 UTC, merged