Pbi 347 css animations
hubmapconsortium/ccf-ui pull request #356
Opened 2020-09-10 21:05 UTC by adphillips2017

Issue #347

2020-09-11 12:51 UTC, bherr2 requested changes
* [ ] Talked with lecross and he suggests speeding up the transitions from 1s to 0.6s. He also says the transition values are in the spec.
* [ ] Could you also add a ripple effect to the buttons like you see on the radio buttons and toggle switches? Let's give all buttons a ripple effect, unless they already have an on-press animation.

2020-09-11 12:51 UTC, bherr2 commented on projects/ccf-rui/src/app/shared/components/visibility-toggle/visibility-toggle.component.ts
> +  styleUrls: ['./visibility-toggle.component.scss'],
Unnecessary change

2020-09-14 13:55 UTC, bherr2 commented
The radius of the ripple causes scrollbars to appear randomly. Reduce the radius and have the ripple come from the middle always (I think that's a setting). Please spend some real time to make sure it looks and acts decent in both Firefox and Chrome.

2020-09-14 18:52 UTC, adphillips2017 commented
> The radius of the ripple causes scrollbars to appear randomly. Reduce the radius and have the ripple come from the middle always (I think that's a setting). Please spend some real time to make sure it looks and acts decent in both Firefox and Chrome.

Okay I made the ripple effect centered.  I'm not seeing any scrollbars appear when using any of the reset icons on Firefox or Chrome. If you are still seeing the scrollbar appear, there's a property I can change to set the ripple radius.

2020-09-14 19:02 UTC, bherr2 commented
> > The radius of the ripple causes scrollbars to appear randomly. Reduce the radius and have the ripple come from the middle always (I think that's a setting). Please spend some real time to make sure it looks and acts decent in both Firefox and Chrome.
> 
> Okay I made the ripple effect centered. I'm not seeing any scrollbars appear when using any of the reset icons on Firefox or Chrome. If you are still seeing the scrollbar appear, there's a property I can change to set the ripple radius.

Yep, that works. One minor thing and then this will be done: you forgot to add ripple to the reset button on the stage.

2020-09-14 19:44 UTC, adphillips2017 commented
> > > The radius of the ripple causes scrollbars to appear randomly. Reduce the radius and have the ripple come from the middle always (I think that's a setting). Please spend some real time to make sure it looks and acts decent in both Firefox and Chrome.
> > 
> > 
> > Okay I made the ripple effect centered. I'm not seeing any scrollbars appear when using any of the reset icons on Firefox or Chrome. If you are still seeing the scrollbar appear, there's a property I can change to set the ripple radius.
> 
> Yep, that works. One minor thing and then this will be done: you forgot to add ripple to the reset button on the stage.

It's there, it's just almost impossible to see because of the black background.  I can change the color to something else easy enough, though.  Should I ask Leonard?

2020-09-14 19:45 UTC, bherr2 commented
> > > > The radius of the ripple causes scrollbars to appear randomly. Reduce the radius and have the ripple come from the middle always (I think that's a setting). Please spend some real time to make sure it looks and acts decent in both Firefox and Chrome.
> > > 
> > > 
> > > Okay I made the ripple effect centered. I'm not seeing any scrollbars appear when using any of the reset icons on Firefox or Chrome. If you are still seeing the scrollbar appear, there's a property I can change to set the ripple radius.
> > 
> > 
> > Yep, that works. One minor thing and then this will be done: you forgot to add ripple to the reset button on the stage.
> 
> It's there, it's just almost impossible to see because of the black background. I can change the color to something else easy enough, though. Should I ask Leonard?

Ok, just change the color using your best judgement. Leonard will review as a whole at the end of the sprint.

2020-09-15 12:54 UTC, bherr2 approved these changes

2020-09-15 12:54 UTC, merged