Pbi about page
hubmapconsortium/ccf-ui pull request #589
Opened 2021-05-20 10:22 UTC by edlu77

- Fixed info modal to display text properly
- Added YouTube player to info modal

2021-05-20 15:22 UTC, lecross requested changes
Regarding the video. Use the About text currently on the site. I'm seeing a huge degradation in video quality when moving to PIP or full-screen. This may be caused by the inline width and height on the iframe tag, removing those may help. I toyed with this but got inconsistent results. For the height of the iframe, in CSS okay to set height to 100% but use a max-height of like 280px or 50%. That should make the video more presentable. This goes for both EUI and RUI. Also, there needs to be a close icon at the top right.

2021-05-21 17:38 UTC, bherr2 requested changes

2021-05-21 17:38 UTC, bherr2 commented on projects/ccf-shared/src/lib/components/info/info-dialog/info-dialog.component.html
> +                  <youtube-player videoId="142hGer4xvU"></youtube-player>
Need to have config for EUI / RUI. This is a blocker.

2021-05-21 17:38 UTC, bherr2 commented
And don't forget the code smell

2021-05-21 18:31 UTC, lecross requested changes
![1a - Home, default, non-consortium – 70](https://user-images.githubusercontent.com/38889248/119182625-01684180-ba28-11eb-91bf-b25fd1cbfe85.png)

Text provided separately.

2021-05-21 18:45 UTC, bherr2 requested changes
Delete `src/assets/dev-data/entities.json`

2021-05-21 19:48 UTC, bherr2 commented on projects/ccf-shared/src/lib/components/info/info-dialog/info-dialog.component.html
> +                <div class="video-player" *ngIf="i === 0 && pageType === 'EUI'">
instead of adding a pageType how about videoId? No need for this sort of hard coding.

2021-05-21 19:49 UTC, bherr2 commented on projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html
> +      <ccf-info-button [pageType]="'RUI'" [infoTitle]="'HuBMAP CCF Registration User Interface 1.0'"></ccf-info-button>
Random: Remove the `1.0` from the infoTitle.

2021-05-21 20:28 UTC, bherr2 commented on projects/ccf-eui/src/app/app.component.html
> +        <ccf-info-button [videoID]="'142hGer4xvU'" [infoTitle]="'HuBMAP CCF Exploration User Interface'" [matTooltip]="'Open Info'">
Do we not have an EUI videoID?

2021-05-21 20:28 UTC, edlu77 commented on projects/ccf-eui/src/app/app.component.html
> +        <ccf-info-button [videoID]="'142hGer4xvU'" [infoTitle]="'HuBMAP CCF Exploration User Interface'" [matTooltip]="'Open Info'">
Not yet

2021-05-21 20:34 UTC, bherr2 approved these changes

2021-05-21 20:34 UTC, merged